apiVersion: v1
kind: Service
metadata:
  name: noobernetes
spec:
  ports:
  - nodePort: 31532
    port: 4000
    protocol: TCP
    targetPort: 4567
  selector:
    app: noobernetes
  type: LoadBalancer

